### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by romeokienzler** [ibmdbanalytics/dashdb_analytic_tools#1]
Hi, 

would you please be so kind and add some sentences how to configure the ODBC settings correctly?

I'm stuck with 

mycon <- idaConnect("DASHDB", "", "")
Warning messages:
1: In odbcDriverConnect("DSN=DASHDB", believeNRows = FALSE) :
  [RODBC] ERROR: state      , code -1531, message [unixODBC][IBM][CLI Driver] SQL1531N  The connection failed because the name specified with the DSN connection string keyword could not be found in either the db2dsdriver.cfg configuration file or the db2cli.ini configuration file.  Data source name specified in the connection string: "DASHDB".
2: In odbcDriverConnect("DSN=DASHDB", believeNRows = FALSE) :
  ODBC connection failed

This is after I've configured the DSN in /etc/odbc.ini - so at least this seems to get picked up...

thanks a lot

**Comment by mwurst** [comment]
Hi Romeo,

did you try to connect with the code that is used in the linreg sample (in the samples directory?

Michael

host.name <- ""
user.name <-""
pwd <- ""
######################################################################

if((nchar(host.name)==0)||(nchar(user.name)==0)||(nchar(pwd)==0))
  stop("Please specify the host.name, user.name and pwd by setting the variables above.")

con <- idaConnect(paste("DASHDB",";Database=BLUDB;Hostname=",host.name,";Port=50000;PROTOCOL=TCPIP;UID=", user.name,";PWD=",pwd,sep=""),"","")

idaInit(con)

**Comment by mwurst** [comment]
you have to just fill in host.name, user.name and pwd

**Comment by romeokienzler** [comment]
Wow, this immediately worked just fine, I love you! :)
