### ISSUE TITLE
Generated spark apps use non existing method

### ISSUE THREAD

**Issue by torsstei** [ibmdbanalytics/dashdb_analytic_tools#10]
Generating and compiling Spark apps results in the following when trying to run the deployed app:

java.lang.NoSuchMethodError: scala\/runtime\/VolatileObjectRef.zero()Lscala\/runtime\/VolatileObjectRef; (loaded from file:\/opt\/ibm\/dashdb_spark\/spark\/lib\/spark-assembly-1.6.2-hadoop2.6.0.jar by sun.misc.Launcher$AppClassLoader@d5701af5) called from class SampleApp$ (loaded from file:\/mnt\/blumeta0\/home\/bluadmin\/spark\/apps\/kmeans_2.11-1.0.jar by sun.misc.Launcher$AppClassLoader@d5701af5)

**Comment by okoethibm** [comment]
version mismatch between scala 2.10 used in dashDB and scala 2.11 used in the container compile environment. fixed by adapting the versions in build.sbt.template
