### ISSUE TITLE
CentOS issue

### ISSUE THREAD

**Issue by dhuszti** [ibmdbanalytics/dashdb_analytic_tools#9]
Hi,
Could you please help me resolving following issue at STEP 6 of docker build? It says Debian cannot reach network, even if Docker host has an established connection.

```
Err:1 http://httpredir.debian.org/debian testing InRelease
  Temporary failure resolving 'httpredir.debian.org'
Err:2 http://http.debian.net/debian sid InRelease
  Temporary failure resolving 'http.debian.net'
...
W: Failed to fetch http://httpredir.debian.org/debian/dists/testing/InRelease  Temporary failure resolving 'httpredir.debian.org'
....
```

Thanks,
Daniel

**Comment by okoethibm** [comment]
This does not sound like a problem with our Dockerfile but like a general issue with network connectivity from your containers. Just tested with the latest update of rocker/rstudio (on Ubuntu) and the image builds fine.
To debug your setup, you can run a container with the base image
    docker run -ti --entrypoint=/bin/bash rocker/rstudio
and then execute the apt-get commands from STEP 6
   rm -rf /var/lib/apt/lists/   && apt-get update   && apt-get -y install procps
this should reproduce the error. In fact, your problem looks like you can't even ping outside hosts from your container.
Check the DNS resolution of your container, look at /etc/resolv.conf in your container and on your docker host and see https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/

**Comment by dhuszti** [comment]
Yes, networking was key issue. Without making this modification on host machine this Docker container wasn't able to access network.

Add following line to file /etc/default/docker

`DOCKER_OPTS="--dns <nameserver_ip>"`

Now everything works fine. Thanks!
